/**
 * Reads public/site-map.svg, adds data-plot attributes + hover CSS to each
 * numbered plot element, and writes src/lib/site-map-svg.ts as an importable
 * string constant. Run whenever the SVG source changes:
 *   node scripts/process-svg.mjs
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(fileURLToPath(import.meta.url), "../..");
const svg = readFileSync(join(root, "public/site-map.svg"), "utf8");

const hoverCss = `<style>
  /* Text layer: renders on top visually but passes mouse events through,
     so hovering over a plot number still hits the plot shape underneath. */
  #layer1 { pointer-events: none; }

  .plot-interactive {
    cursor: pointer;
    /* all: respond across the full shape area, not just where paint is visible.
       Without this, transparent-fill rects only fire on the stroke border. */
    pointer-events: all;
    transition: fill 0.12s ease, fill-opacity 0.12s ease;
  }
  .plot-interactive:hover {
    fill: #4a7c4e !important;
    fill-opacity: 0.28 !important;
  }
  .plot-interactive:active {
    fill-opacity: 0.45 !important;
  }
  /* Applied at runtime by InteractiveSiteMap for plots marked available */
  .plot-available {
    fill: #4a7c4e !important;
    fill-opacity: 0.18 !important;
  }
  .plot-available:hover {
    fill-opacity: 0.38 !important;
  }
  .plot-available:active {
    fill-opacity: 0.55 !important;
  }
</style>`;

function addPlotAttrs(elem) {
  const labelMatch = elem.match(/inkscape:label="([^"]+)"/);
  if (!labelMatch) return elem;
  const label = labelMatch[1].trim();
  if (!/^\d+[ab]?$/.test(label)) return elem;
  return elem.replace(
    /\s*\/>/,
    `\n       data-plot="${label}"\n       class="plot-interactive" />`,
  );
}

const plotsLayerRe = /(<g[^>]*id="layer2"[^>]*>)([\s\S]*?)(<\/g>)/;
const processed = svg
  .replace(plotsLayerRe, (_, open, content, close) => {
    const updated = content
      .replace(/<rect[^/]*\/>/g, addPlotAttrs)
      .replace(/<path[^/]*\/>/g, addPlotAttrs);
    return open + updated + close;
  })
  .replace("</svg>", hoverCss + "\n</svg>");

const count = (processed.match(/class="plot-interactive"/g) ?? []).length;

mkdirSync(join(root, "src/lib"), { recursive: true });
writeFileSync(
  join(root, "src/lib/site-map-svg.ts"),
  `// Auto-generated by scripts/process-svg.mjs — do not edit by hand.\nexport const siteMapSvg = ${JSON.stringify(processed)};\n`,
);

console.log(`✓ Tagged ${count} plot elements → src/lib/site-map-svg.ts`);
